runtime: python37
service: default

handlers:
  - url: /([^.]+)/?$  # urls with no dot in them
    static_files: dist/front/index.html
    upload: dist/front/index.html
  - url: /
    static_files: dist/front/index.html
    upload: dist/front/index.html
  - url: /(.*)
      static_files: dist/front/(.*)
      upload: dist/front/(.*)
