steps:
  - id: 'Install Node modules'
    name: 'node:14.16.0'
    entrypoint: 'npm'
    args: ['i']

  - id: 'Build application'
    name: 'node:14.16.0'
    entrypoint: 'npm'
    args: ['run', 'build_dev']

  - id: 'Deploy front on AppEngine'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--version', '$COMMIT_SHA']
