export const constants = {
  USER: '/users/',
  USER_UPDATE: '/users/update/',
  USER_ID: '/users/id/',
  USER_SEARCH: '/users/search/',
  AUTH: '/auth/',
  AUTH_TOKEN: '/auth/token/',
  RECIPE_CATEGORY: '/recipe_category/',
  RECIPE_COOKING_TYPE: '/recipe_cooking_type/',
  RECIPE: '/recipe/',
  RECIPE_MEDIA: '/recipe/media/',
  RECIPE_LIKED: '/recipe/liked_recipe/',
  RECIPE_WALL: '/recipe/wall/',
  RECIPE_CREATOR: '/recipe/creator/',
  RECIPE_THUMBNAIL: '/recipe/thumbnail_media/',
  RECIPE_VIDEO: '/recipe/video_media/',
  BOOK: '/book/',
  BOOK_TEMPLATE: '/book/template/',
  BOOK_PREVIEW: '/book/preview/',
  BOOK_COVER: '/book/cover/',
  BOOK_BROKER: '/book/broker/',
  BOOK_CREATOR: '/book/creator/',
};
