export const constants = {
  USER: '/users/',
  USER_UPDATE: '/users/update/',
  USER_ID: '/users/id/',
  AUTH: '/auth/',
  AUTH_TOKEN: '/auth/token/',
  RECIPE_CATEGORY: '/recipe_category/',
  RECIPE: '/recipe/',
  RECIPE_MEDIA: '/recipe/media/',
  RECIPE_LIKED: '/recipe/liked_recipe/',
  RECIPE_WALL: '/recipe/wall/',
  RECIPE_COOKING_TYPE: '/recipe_cooking_type/',
  RECIPE_CREATOR: '/recipe/creator/',
  RECIPE_THUMBNAIL: '/recipe/thumbnail_media/',
  RECIPE_VIDEO: '/recipe/video_media/',
};
